### ISSUE TITLE
Script crashes

### ISSUE THREAD

**Issue by KeinNameVorhanden** [IceQ1337/SteamBanChecker#21]
```
[Thu, 06 Aug 2020 17:08:17 GMT] [INFO] [Telegram] start > Telegram Bot Started.
[Thu, 06 Aug 2020 17:08:18 GMT] [INFO] [SteamAPI] Ban > Profile: 76561199037747128 Type: game
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received null
    at validateString (internal/validators.js:120:11)
    at normalizeSpawnArguments (child_process.js:406:3)
    at Object.spawn (child_process.js:542:16)
    at Function.spawn (/root/SteamBanChecker/node_modules/cross-spawn/index.js:87:19)
    at spawnPhantom (/root/SteamBanChecker/node_modules/webshot-node/lib/webshot.js:201:32)
    at spawn (/root/SteamBanChecker/node_modules/webshot-node/lib/webshot.js:105:14)
    at /root/SteamBanChecker/node_modules/webshot-node/lib/webshot.js:117:16
    at suppressedCallback (fs.js:215:5)
    at FSReqCallback.oncomplete (fs.js:156:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
run in forever

node: v12.18.3
npm: v6.14.6
Ubuntu 16.04.6 LTS (Xenial Xerus)

**Comment by IceQ1337** [comment]
Ich kann den Fehler nicht reproduzieren. Hat der ausführende Benutzer Schreibrechte für das Screenshot Verzeichnis? Wenn das Problem wiederholt auftritt, versuch bitte herauszufinden, wie ich das Problem bei mir reproduzieren kann.
